### ISSUE TITLE
Upgrade to 

### ISSUE THREAD

**Issue by simerplaha** [weiyinteo/scalajs-react-bootstrap#1]
@weiyinteo 
Thanks heaps for going through the effort creating this library.

I've made some changes to it to upgrade to the latest Scala, scalajs and Scala-reactJs. If you have not done the upgrade already. I've added the necessary upgrades to a fork of this project 
https://github.com/simerplaha/scalajs-react-bootstrap

Please let me know if you are happy for this to be merged into your branch.

**Comment by weiyinteo** [comment]
@simerplaha 
Sure. Can you create a PR?

Thanks.

**Comment by simerplaha** [comment]
I've just messed up the history and can't do a PR. I will try to fix this over the weekend.
